import { OnInit, EventEmitter } from '@angular/core';
import { CommonPaymentService } from '../serivces/common-payment.service';
import * as i0 from "@angular/core";
export declare class PaymentDetailsComponent implements OnInit {
    private commonService;
    paymentMethodType: any;
    paymentEnable: any;
    settings: any;
    devicePayment: boolean;
    clientTelephone: any;
    testResult: any;
    postCode: any;
    isGocardlessEnabled: any;
    paymentOption: any;
    valid(paymentEnable: any): void;
    genericPaymentDetails: any;
    tip: any;
    total: number;
    paymentMethodAllowed: any;
    paymentMethod: any;
    paymentCompleted: boolean;
    canDoWalletPay: boolean;
    walletPayLogoName: string;
    walletPayDesc: string;
    walletDetails: any;
    amountToBePaid: any;
    pendingAmount: any;
    portalName: any;
    emitter: EventEmitter<string>;
    payEmitter: EventEmitter<any>;
    payOptionEmitter: EventEmitter<any>;
    constructor(commonService: CommonPaymentService);
    ngOnInit(): void;
    changePaymentOption(option: string, selected: any): void;
    paymentSelected(value: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PaymentDetailsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PaymentDetailsComponent, "lib-payment-details", never, { "genericPaymentDetails": "genericPaymentDetails"; "tip": "tip"; "total": "total"; }, { "emitter": "emitter"; "payEmitter": "payEmitter"; "payOptionEmitter": "payOptionEmitter"; }, never, never>;
}
