import { OnInit, EventEmitter } from '@angular/core';
import { CommonPaymentService } from '../serivces/common-payment.service';
import * as i0 from "@angular/core";
export declare class PaymentDetailsComponent implements OnInit {
    private commonService;
    paymentMethodType: any;
    paymentEnable: any;
    settings: any;
    devicePayment: boolean;
    clientTelephone: any;
    testResult: any;
    valid(paymentEnable: any): void;
    genericPaymentDetails: any;
    storedCard: any;
    tip: any;
    paymentMethodAllowed: any;
    paymentMethod: any;
    paymentCompleted: boolean;
    canDoWalletPay: boolean;
    walletPayLogoName: string;
    walletPayDesc: string;
    walletDetails: any;
    emitter: EventEmitter<string>;
    payEmitter: EventEmitter<any>;
    constructor(commonService: CommonPaymentService);
    ngOnInit(): void;
    paymentSelected(value: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PaymentDetailsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PaymentDetailsComponent, "lib-payment-details", never, { "genericPaymentDetails": "genericPaymentDetails"; "storedCard": "storedCard"; "tip": "tip"; }, { "emitter": "emitter"; "payEmitter": "payEmitter"; }, never, never>;
}
