import { EventEmitter, OnInit } from '@angular/core';
import { CommonPaymentService } from '../serivces/common-payment.service';
import { ActivatedRoute } from '@angular/router';
import * as i0 from "@angular/core";
export declare class PaymentCompleteComponent implements OnInit {
    private commonPaymentService;
    private activatedRoute;
    valid: boolean;
    cardDetails: any;
    completePageDetails: any;
    pending: boolean;
    userResponse: any;
    paymentCharges: any;
    cardImg: string;
    paymentFailed: boolean;
    loading: boolean;
    completePaymentData: any;
    items: any;
    balance: number;
    tip: number;
    uuid: any;
    amount: number;
    paymentType: string;
    close: EventEmitter<boolean>;
    cardCharges: any;
    cardCharge: number;
    constructor(commonPaymentService: CommonPaymentService, activatedRoute: ActivatedRoute);
    ngOnInit(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<PaymentCompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PaymentCompleteComponent, "lib-payment-complete", never, { "valid": "valid"; "cardDetails": "cardDetails"; "completePageDetails": "completePageDetails"; }, { "close": "close"; }, never, never>;
}
